-- AlterTable
ALTER TABLE "labour_payments" ADD COLUMN     "advanceAdjustment" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonus" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "other" DOUBLE PRECISION NOT NULL DEFAULT 0;
